<?php if(get_sub_field('icon_bullet_points_row_icon') == "icon_4stars"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_4stars.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_camera"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_Camera.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_check"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_Check.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_circlestar"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_CircleStar.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_creditcard"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_CreditCard.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_deposit"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_Deposit.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_fastcash"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_FastCash.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_goldseal"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_GoldSeal.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_location"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_Location.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_locationcontrol"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_LocationControl.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_paymentcode"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_PaymentCode.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_phone"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_Phone.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_pricetagoverpaying"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_PriceTag_Overpaying.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_profile"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_Profile.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_radar"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_Radar.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_releasepayment"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_ReleasePayment.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_signature"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_Signature.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_statusupdate"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_StatusUpdate.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_trustshield"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_TrustShield.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_alert"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_Alert.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_calculator"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_Calculator.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_carriercard"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_CarrierCard.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_insights"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_Insights.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_pricetagpercent"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_PriceTag_Percent.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_reach"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_Reach.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_truck"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_Truck.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_boat"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_Boat.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_fuelcard"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_FuelCard.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_gavel"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_Gavel.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_lodging"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_Lodging.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_wheel"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_Wheel.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_compass"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_Compass.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_desktop"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_Desktop.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_pricetag"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_PriceTag.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_truck2"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_Truck2.svg'); ?>
<?php elseif (get_sub_field('icon_bullet_points_row_icon') == "icon_truckload"): ?>
    <?php include( get_template_directory() . '/images/icons/icon_TruckLoad.svg'); ?>
<?php endif; ?>